resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 40
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 500
  instances:
    simple_circuit_breaker:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 3s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
  instances:
    simple_retry:
      baseConfig: default